project: 
  type: website
website: 
  page-navigation: true
  favicon: images/favicon.ico
  back-to-top-navigation: true
  page-footer:
    border: true
    center:
      - text: "Website Owner"
        href: https://www.fisheries.noaa.gov/about/southwest-fisheries-science-center
        target: _blank
      - text: "Contact"
        href: https://www.fisheries.noaa.gov/contact/southwest-fisheries-science-center
        target: _blank
      - text: "NOAA"
        href: https://www.noaa.gov/
        target: _blank
      - text: "Privacy Policy"
        href: https://www.noaa.gov/privacy.html
        target: _blank
      - text: "Information Quality"
        href: https://www.noaa.gov/organization/information-technology/policy-oversight/information-quality
        target: _blank
      - text: "Disclaimer"
        href: https://www.fisheries.noaa.gov/national/about-us/website-policies-and-disclaimers
        target: _blank
    right:
      - text: "<img src='/images/logos/doc_logo_black.gif' style='height: 50px; width: auto;'/>"
        href: https://www.commerce.gov/
  navbar:
    title: "NEAP Collaborators"
    background: $navbar-bg
    logo: "images/logos/noaa_logo.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/lmdewitt/NEAP-Collaborators

    style: "docked"
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resources"
        href: resources.qmd
  sidebar:
    title: "NEAP Links:"
    id: main-docs
    style: "docked"
    collapse-level: 2
    contents:
      - text: "<i>NEAP Links</i>"
      - section: "<b>Collaborators Tags Tests</b>"
        contents:
          - text: "By Topical Expertise"
            href: index.qmd
          - text: "All Tags"
            href: all_categories.qmd
      - section: "<b>General NEAP links</b>"
        contents:
          - text: "IEA"
            href: https://www.integratedecosystemassessment.noaa.gov/
      - section: "<b>NEAP/IEA Data Group Web pages</b>"
        contents:
          - text: "NEAP/IEA Guidance Doc"
            href: https://iea-data.github.io/IEA_Data_Guidance_Doc/
          - text: IEA-Data Discussion Board
            href: https://github.com/IEA-Data/Discussion_Board/discussions
          - text: FY25-28 IEA Data Working Group Strategic Plan
            href: https://docs.google.com/document/d/1XBplEGRCfYjrGG4Ch3V_8l4xiJ7C1eFB03vimfslNS8/edit?tab=t.0#heading=h.lel32f7gy7db
      - section: "<b>Repositories</b>"
        contents:
          - text: "NEAP/IEA Data Working Group"
            href: http://www.github.com/IEA-Data
format:
  html:
    backgroundcolor: "#fdfdfd"
    theme:
      light: [cosmo, theme.scss] 
    css: style.css
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-icon: true
    toc: true

filters:
  - include-files.lua
  - quarto

engine: knitr  
